# Generated by Django 3.0.5 on 2020-04-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_filename', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('image_caption', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('strunz_classification', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('crystal_system', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('unit_cell', models.TextField(blank=True, null=True)),
                ('crystal_symmetry', models.TextField(blank=True, null=True)),
                ('cleavage', models.CharField(blank=True, max_length=255, null=True)),
                ('mohs_scale_hardness', models.TextField(blank=True, null=True)),
                ('luster', models.TextField(blank=True, null=True)),
                ('streak', models.CharField(blank=True, max_length=255, null=True)),
                ('diaphaneity', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('optical_properties', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('refractive_index', models.TextField(blank=True, null=True)),
                ('crystal_habit', models.TextField(blank=True, null=True)),
                ('specific_gravity', models.TextField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
